import http from "node:http";
import fs from "node:fs";
import {Keypair,VersionedTransaction} from "@solana/web3.js";
import bs58 from "bs58";
const USDC="EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",PATH=process.env.SOLANA_EXECUTOR_STATE_PATH||"/app/data/solana_executor.json",ACK="I_ACCEPT_THE_25_USD_SOLANA_EARLY_RISK";
const num=(v,d=0)=>String(v??"").trim()!==""&&Number.isFinite(Number(v))?Number(v):d,env=(a,b="")=>process.env[a]||process.env[b]||"";
const cfg={discovery:env("SOLANA_DISCOVERY_URL").replace(/\/$/,""),jupiter:env("JUPITER_API_KEY"),helius:env("HELIUS_API_KEY"),secret:env("SOLANA_WALLET_PRIVATE_KEY"),enabled:env("SOLANA_EXECUTOR_ENABLED")==="true",live:env("SOLANA_LIVE_ENABLED")==="true"&&env("SOLANA_LIVE_ACK")===ACK,
 entry:Math.min(3,Math.max(1,num(env("SOLANA_MAX_ENTRY_USD"),3))),total:Math.min(6,Math.max(3,num(env("SOLANA_MAX_TOTAL_EXPOSURE_USD"),6))),max:Math.min(2,Math.max(1,num(env("SOLANA_MAX_POSITIONS"),2))),stop:Math.min(.25,Math.max(.08,num(env("SOLANA_STOP_LOSS_PCT"),.18))),target:Math.min(1,Math.max(.15,num(env("SOLANA_TAKE_PROFIT_PCT"),.4))),trail:Math.min(.25,Math.max(.08,num(env("SOLANA_TRAILING_STOP_PCT"),.15))),minPaper:Math.max(20,num(env("SOLANA_MIN_PAPER_OBSERVATIONS"),50)),
 paperEntry:Math.min(3,Math.max(.5,num(env("SOLANA_PAPER_ENTRY_USD"),2))),paperTotal:Math.min(25,Math.max(3,num(env("SOLANA_PAPER_TOTAL_EXPOSURE_USD"),20))),paperMax:Math.min(10,Math.max(1,num(env("SOLANA_PAPER_MAX_POSITIONS"),8))),
 emailEnabled:env("SOLANA_EMAIL_REPORT_ENABLED")==="true",recipients:env("SOLANA_EMAIL_RECIPIENTS","FOREX_EMAIL_RECIPIENTS").split(",").map(x=>x.trim()).filter(Boolean),from:env("SOLANA_EMAIL_FROM","FOREX_EMAIL_FROM"),client:env("SOLANA_EMAIL_GMAIL_CLIENT_ID","FOREX_EMAIL_GMAIL_CLIENT_ID"),clientSecret:env("SOLANA_EMAIL_GMAIL_CLIENT_SECRET","FOREX_EMAIL_GMAIL_CLIENT_SECRET"),refresh:env("SOLANA_EMAIL_GMAIL_REFRESH_TOKEN","FOREX_EMAIL_GMAIL_REFRESH_TOKEN")};
const fresh=()=>{const now=new Date().toISOString();return{version:2,createdAt:now,paperStartedAt:now,paperObservations:0,paperPositions:[],paperFills:[],paperRealizedPnlUsd:0,positions:[],fills:[],errors:[],seen:{},email:{sentCount:0}}};
function load(){try{const x=JSON.parse(fs.readFileSync(PATH,"utf8"));return{...fresh(),...x,version:2,paperPositions:x.paperPositions||[],paperFills:x.paperFills||[],paperObservations:(x.paperFills||[]).filter(f=>f.action==="SELL").length}}catch{return fresh()}}let state=load();
function save(){fs.mkdirSync(PATH.slice(0,PATH.lastIndexOf("/")),{recursive:true});fs.writeFileSync(`${PATH}.tmp`,JSON.stringify(state));fs.renameSync(`${PATH}.tmp`,PATH)}
let wallet=null;try{if(cfg.secret){const b=bs58.decode(cfg.secret.trim());wallet=b.length===64?Keypair.fromSecretKey(b):b.length===32?Keypair.fromSeed(b):(()=>{throw Error(`decoded key is ${b.length} bytes, expected 32 or 64`)})()}}catch(e){state.errors.unshift(`wallet key invalid: ${e.message}`)}
const exposure=a=>a.reduce((n,p)=>n+p.entryUsd,0),closed=()=>state.paperFills.filter(f=>f.action==="SELL");
function blockers(){const b=[];if(!cfg.enabled)b.push("executor disabled");if(!cfg.discovery)b.push("discovery URL missing");if(!cfg.jupiter)b.push("Jupiter key missing");if(!cfg.helius)b.push("Helius key missing");if(!wallet)b.push("wallet key missing or invalid");if(!cfg.live)b.push("live acknowledgement not armed");if(state.paperObservations<cfg.minPaper)b.push(`closed paper trades ${state.paperObservations}/${cfg.minPaper}`);if(Date.now()-Date.parse(state.paperStartedAt)<864e5)b.push("24-hour paper soak not completed");return b}
function emailBlockers(){const b=[];if(!cfg.emailEnabled)b.push("email disabled");if(!cfg.recipients.length)b.push("recipients missing");if(!cfg.from)b.push("from address missing");if(!cfg.client)b.push("Gmail client ID missing");if(!cfg.clientSecret)b.push("Gmail client secret missing");if(!cfg.refresh)b.push("Gmail refresh token missing");return b}
function publicState(){const address=wallet?.publicKey.toString()||"";return{...state,seen:undefined,walletSuffix:address.slice(-6),live:cfg.live,ready:!blockers().length,blockers:blockers(),email:{...state.email,enabled:cfg.emailEnabled,recipientCount:cfg.recipients.length,blockers:emailBlockers()},limits:{live:{entryUsd:cfg.entry,totalUsd:cfg.total,maxPositions:cfg.max},paper:{entryUsd:cfg.paperEntry,totalUsd:cfg.paperTotal,maxPositions:cfg.paperMax},stopPct:cfg.stop,targetPct:cfg.target,trailPct:cfg.trail}}}
async function json(url,opt={}){const r=await fetch(url,opt);if(!r.ok)throw Error(`${r.status} ${await r.text()}`);return r.json()}
async function rpc(method,params){return json(`https://mainnet.helius-rpc.com/?api-key=${encodeURIComponent(cfg.helius)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({jsonrpc:"2.0",id:1,method,params})})}
async function balances(){const owner=wallet.publicKey.toString(),[sol,tokens]=await Promise.all([rpc("getBalance",[owner]),rpc("getTokenAccountsByOwner",[owner,{mint:USDC},{encoding:"jsonParsed"}])]);state.balances={sol:num(sol.result?.value)/1e9,usdc:(tokens.result?.value||[]).reduce((n,x)=>n+num(x.account?.data?.parsed?.info?.tokenAmount?.uiAmount),0),checkedAt:new Date().toISOString()};return state.balances}
async function order(inputMint,outputMint,amount){const q=new URLSearchParams({inputMint,outputMint,amount:String(amount),taker:wallet.publicKey.toString()});return json(`https://api.jup.ag/swap/v2/order?${q}`,{headers:{"x-api-key":cfg.jupiter}})}
async function execute(o){if(!o.transaction)throw Error("Jupiter order has no transaction");const tx=VersionedTransaction.deserialize(Buffer.from(o.transaction,"base64"));tx.sign([wallet]);return json("https://api.jup.ag/swap/v2/execute",{method:"POST",headers:{"content-type":"application/json","x-api-key":cfg.jupiter},body:JSON.stringify({signedTransaction:Buffer.from(tx.serialize()).toString("base64"),requestId:o.requestId,lastValidBlockHeight:o.lastValidBlockHeight})})}
async function paperBuy(c){const o=await order(USDC,c.mint,Math.round(cfg.paperEntry*1e6)),qty=num(o.outAmount||o.outputAmount);if(!qty)throw Error(`no paper buy route for ${c.mint}`);const at=new Date().toISOString(),id=`paper:${c.mint}:${Date.now()}`;state.paperPositions.push({id,mint:c.mint,symbol:c.symbol||c.mint.slice(0,6),quantity:qty,entryUsd:cfg.paperEntry,highUsd:cfg.paperEntry,openedAt:at,score:c.score,walletEvidence:c.qualified_wallet_count||0});state.paperFills.unshift({id,action:"BUY",at,mint:c.mint,symbol:c.symbol,entryUsd:cfg.paperEntry,score:c.score,walletEvidence:c.qualified_wallet_count||0});return true}
async function paperClose(p,reason,o){const proceeds=num(o.outAmount||o.outputAmount)/1e6;if(!proceeds)return false;const pnl=proceeds-p.entryUsd;state.paperFills.unshift({id:`close:${p.id}`,action:"SELL",at:new Date().toISOString(),mint:p.mint,symbol:p.symbol,reason,proceedsUsd:proceeds,realizedPnlUsd:pnl,returnPct:pnl/p.entryUsd});state.paperPositions=state.paperPositions.filter(x=>x.id!==p.id);state.paperRealizedPnlUsd=num(state.paperRealizedPnlUsd)+pnl;state.paperObservations++;return true}
async function supervisePaper(){let changed=false;for(const p of [...state.paperPositions])try{const o=await order(p.mint,USDC,Math.floor(p.quantity)),mark=num(o.outAmount||o.outputAmount)/1e6;if(!mark)continue;p.markUsd=mark;p.markedAt=new Date().toISOString();p.highUsd=Math.max(num(p.highUsd,p.entryUsd),mark);const r=mark/p.entryUsd-1,reason=r<=-cfg.stop?"STOP_LOSS":r>=cfg.target?"TAKE_PROFIT":mark<=p.highUsd*(1-cfg.trail)&&p.highUsd>p.entryUsd?"TRAILING_STOP":Date.now()-Date.parse(p.openedAt)>=864e5?"MAX_HOLD_24H":"";if(reason)changed=await paperClose(p,reason,o)||changed}catch(e){p.markError=e.message.slice(0,180)}return changed}
async function buy(c){const o=await order(USDC,c.mint,Math.round(cfg.entry*1e6)),r=await execute(o);if(r.status!=="Success"||num(r.code)!==0)throw Error(`buy failed: ${r.error||r.code}`);const fill={id:r.signature,action:"BUY",mint:c.mint,symbol:c.symbol,at:new Date().toISOString(),outputUnits:num(r.totalOutputAmount),score:c.score};state.fills.unshift(fill);state.positions.push({mint:c.mint,symbol:c.symbol,quantity:fill.outputUnits,entryUsd:cfg.entry,highUsd:cfg.entry,openedAt:fill.at,entrySignature:r.signature})}
async function sell(p,reason,o){const r=await execute(o||await order(p.mint,USDC,Math.floor(p.quantity)));if(r.status!=="Success"||num(r.code)!==0)throw Error(`sell failed: ${r.error||r.code}`);const proceeds=num(r.totalOutputAmount)/1e6;state.fills.unshift({id:r.signature,action:"SELL",reason,mint:p.mint,symbol:p.symbol,at:new Date().toISOString(),realizedPnlUsd:proceeds-p.entryUsd});state.positions=state.positions.filter(x=>x.entrySignature!==p.entrySignature)}
async function superviseLive(){for(const p of [...state.positions]){const o=await order(p.mint,USDC,Math.floor(p.quantity)),mark=num(o.outAmount||o.outputAmount)/1e6;if(!mark)continue;p.highUsd=Math.max(num(p.highUsd,p.entryUsd),mark);const r=mark/p.entryUsd-1,reason=r<=-cfg.stop?"STOP_LOSS":r>=cfg.target?"TAKE_PROFIT":mark<=p.highUsd*(1-cfg.trail)&&p.highUsd>p.entryUsd?"TRAILING_STOP":Date.now()-Date.parse(p.openedAt)>=864e5?"MAX_HOLD_24H":"";if(reason)await sell(p,reason,o)}}
function report(){const done=closed(),wins=done.filter(x=>x.realizedPnlUsd>0).length,rows=state.paperFills.slice(0,12).map(f=>`<tr><td>${f.at}</td><td>${f.action}</td><td>${f.symbol||f.mint.slice(0,6)}</td><td>${f.reason||"ENTRY"}</td><td>${f.realizedPnlUsd==null?"—":`$${f.realizedPnlUsd.toFixed(4)}`}</td></tr>`).join("");return `<h2>Solana Early Discovery — Paper Report</h2><p><b>PAPER ONLY — no funds were spent.</b></p><p>Closed: ${done.length}/${cfg.minPaper} · Win rate: ${done.length?(wins/done.length*100).toFixed(1):"0.0"}% · Realized P&amp;L: $${num(state.paperRealizedPnlUsd).toFixed(4)} · Open: ${state.paperPositions.length}</p><p>Wallet: …${wallet?.publicKey.toString().slice(-6)||"missing"} · Live blockers: ${blockers().join("; ")||"none"}</p><table border="1" cellpadding="5"><tr><th>UTC</th><th>Action</th><th>Token</th><th>Reason</th><th>P&amp;L</th></tr>${rows||"<tr><td colspan=5>No paper fills yet</td></tr>"}</table>`}
async function email(hasTradeEvent=false){if(!hasTradeEvent||emailBlockers().length)return false;const body=new URLSearchParams({client_id:cfg.client,client_secret:cfg.clientSecret,refresh_token:cfg.refresh,grant_type:"refresh_token"}),t=await json("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body});const subject=`[TRADE] Solana paper action — ${state.paperObservations} closed — $${num(state.paperRealizedPnlUsd).toFixed(2)} P&L`,mime=[`From: ${cfg.from}`,`To: ${cfg.recipients.join(", ")}`,`Subject: ${subject}`,"MIME-Version: 1.0","Content-Type: text/html; charset=UTF-8","",report()].join("\r\n");await json("https://gmail.googleapis.com/gmail/v1/users/me/messages/send",{method:"POST",headers:{authorization:`Bearer ${t.access_token}`,"content-type":"application/json"},body:JSON.stringify({raw:Buffer.from(mime).toString("base64url")})});state.email={...state.email,lastSentAt:new Date().toISOString(),lastError:"",sentCount:num(state.email.sentCount)+1,mode:"TRADE_EVENTS_ONLY"};return true}
async function tick(){if(!cfg.enabled||!cfg.discovery)return;const data=await json(`${cfg.discovery}/candidates`),candidates=data.candidates||[];let changed=await supervisePaper();for(const c of candidates.filter(x=>x.qualified)){if(state.seen[c.mint])continue;state.seen[c.mint]=data.scanned_at||new Date().toISOString();if(state.paperPositions.length<cfg.paperMax&&exposure(state.paperPositions)+cfg.paperEntry<=cfg.paperTotal)changed=await paperBuy(c)||changed}if(wallet&&cfg.helius)try{await balances()}catch(e){state.balanceError=e.message.slice(0,180)}if(!blockers().length){if(state.balances.usdc<cfg.entry||state.balances.sol<.005)throw Error("wallet funding below live minimum");await superviseLive();for(const c of candidates.filter(x=>x.qualified)){if(state.positions.length>=cfg.max||exposure(state.positions)+cfg.entry>cfg.total)break;if(!state.positions.some(p=>p.mint===c.mint))await buy(c)}}try{await email(changed)}catch(e){state.email={...state.email,lastError:e.message.slice(0,250),lastAttemptAt:new Date().toISOString()}}save()}
const fail=e=>{state.errors.unshift(`${new Date().toISOString()} ${e.message}`);state.errors=state.errors.slice(0,20);save()};setInterval(()=>tick().catch(fail),Math.max(10,num(env("SOLANA_EXECUTOR_INTERVAL_SECONDS"),20))*1000);http.createServer((req,res)=>{if(!["/health","/status"].includes(req.url)){res.writeHead(404).end();return}const p=publicState(),body=JSON.stringify(req.url==="/health"?{service:"solana-executor",...p,positions:undefined,fills:undefined,paperFills:undefined,errors:state.errors.slice(0,3)}:p);res.writeHead(200,{"content-type":"application/json"});res.end(body)}).listen(num(env("PORT"),8080));tick().catch(fail);
